### ISSUE TITLE
No go on installation. Key will simply not verify

### ISSUE THREAD

**Issue by Sinnedcoder** [LayoutXML/SABS#48] opened 2018-03-23 16:43 UTC
what else is there? Followed all the directions. Was asked to "Submit Key" and become administrator in the "submit key" box

**Comment by LayoutXML** [comment] 2018-03-23 16:46
Can't help with anything. Activation is on Samsung's side. Make sure the key is correct (128 bite, legacy), you have changed the package name, knox is not tripped, you have internet connection, key is not blocked etc. You can also contact Samsung - say that you want to develop and your developer key is not working. Don't mention SABS just in case. I'm closing the issue because the issue is not on me and I can't do anything about it.

**Closed by LayoutXML** 2018-03-23 16:46 UTC
Labels: duplicate, help wanted
