### ISSUE TITLE
App crashes for individual app management 

### ISSUE THREAD

**Issue by MGFlaccid** [LayoutXML/SABS#18] opened 2018-03-02 14:05 UTC
Whenever I select "Manage Blocking in Apps" in the settings menu, the app crashes and resets. I've reset my phone, and reinstalled the app as well to no effect. 

Running version 0.07
Samsung Note 8
Android 7.11
Non-Rooted

**Comment by Mike-BITW** [comment] 2018-03-02 14:20
Cannot duplicate at all with any recent  builds on my N8 running Nougat 7.1.1. Which specific version/build are you running. Have you looked at your logs to see what causes that crash?

**Comment by MGFlaccid** [comment] 2018-03-02 14:25
I'm gonna sound like an idiot, but is this a specific SABS log file, or a system wide one? I checked the entire app and the app folder and can't find anything resembling a link error log feature.

**Comment by Mike-BITW** [comment] 2018-03-02 14:37
I was referring to your system logs.  Where and how did you get your copy of SABS? If you patched it with APK Editor Pro or similar tool, it's very possible that it got corrupted. Before you spend too much time on this, it might be wise to compile the current one from here.

**Comment by MGFlaccid** [comment] 2018-03-02 14:41
I obtained and compiled the version uploaded here; I didn't trust APK Editor Pro to get it done. Hmm... I'm at work right now, but I'm going to attempt to recompile and try again later today when I'm home.

**Comment by LayoutXML** [comment] 2018-03-02 18:00
I also think something happened during downloading the source code, installing sdks, android studio or compiling app. With 4000 downloads, this is the first complaint that it crashes on that screen.

**Comment by kennethpangky** [comment] 2018-03-02 23:32
I'm seeing it happen as well. Same device, same versions.

**Comment by Mike-BITW** [comment] 2018-03-02 23:36
Which  specific Note8 model are you two using?

**Comment by kennethpangky** [comment] 2018-03-02 23:40
https://youtu.be/40aO4PRmYe0

SM-N950F/DS

International dual sim.

**Comment by MGFlaccid** [comment] 2018-03-02 23:43
SM-N50U
Just a regular Verizon model

**Comment by MGFlaccid** [comment] 2018-03-02 23:43
I'm watching their video, exact same symptoms as mine

**Comment by Mike-BITW** [comment] 2018-03-02 23:50
@kennethpangky: Ah, Exynos. I'm on a Snapdragon 950U with TMB (T-Mobile) CSC. 

@MGFlaccid: yes, but which exact model number (from your "About Phone" screen)? 

Any chance you could share the system log entries around crash time?

**Comment by MGFlaccid** [comment] 2018-03-02 23:56
That's the model number I have. Single SIM,  nothing special.

SM-N950U, that's all. It seems I did omit the "9" for some stupid reason.

**Comment by Mike-BITW** [comment] 2018-03-03 00:09
OK, then we can rule out model-specific issues, and I doubt that a difference in CSC would trigger a crash. The **logs** would be extremely helpful!

**Comment by MGFlaccid** [comment] 2018-03-03 00:23
Apologies for the ignorance, but how does one access the logs without root? All solutions I can find seem to require root...

**Comment by Mike-BITW** [comment] 2018-03-03 00:40
Have you tried the logcat app (on the Play Store)?  SABS has access to its own logs and maybe @NeedleGames will add a UI for that later on, but chances are the crash is coming from something else.

If needed, SABS makes it easy to add the :READ_LOGS to any app that needs it.

**Comment by MGFlaccid** [comment] 2018-03-03 06:28
I'm sorry to be a headache, but "System Info Pro for Android" does not seem to work. I've given it permission for log access as described, but its logs only cover "System Info Pro for Android" functions and nothing else. 

I'm really sorry to keep bothering you folks without giving clearer info, really. I don't know what happened; it worked fine in 0.0.6, but as soon as 0.0.7 was compiled and installed, individual app blocking was disabled. I'd roll back, but the port 53 fix in 7 was so good it's hard to go back. I just hope to figure this error out: it sucks to have to deactivate SABS every time I want to see the images in an eBay listing, instead of just whitelisting the app. 

If you guys can't help me, it's more my fault for not being able to provide clear information of my problem.

**Comment by LayoutXML** [comment] 2018-03-03 07:15
When you visit eBay and get images blocked, what new blocked url comes up under recent activity in SABS? If you tell me that I can unblock it. Keep in mind that to refresh it, you have to reopen the app.

It would be perfect if you hooked your phone up with the computer and ran the app from android studio again (shift+f10). Open LOGCAT on the lower right parts of the computer screen, set the mode to verbose and remove all filters, delete search field entries, turn on regex. When you start seeing some lines running in the logcat, open the screen on SABS that makes the app crash. On yoir computer you should see some red error logs. Copy the whole log and send it to me. This will show me why it's crashing.

**Comment by Mike-BITW** [comment] 2018-03-03 08:32
I don't know why you get those crashes, but for eBay images, are you sure you're not blocking "**i.ebayimg.com**"?  Look closely at your input files, or simply whitelist "**i.ebayimg.com**" then turn SABS off then back on. No need to whitelist the entire app!

**Comment by MGFlaccid** [comment] 2018-03-04 01:30
I'll say this, whatever caused the crash seems to be gone with the 0.0.8 update. And I took your advice on the whitelist as well, thank you.

**Comment by kennethpangky** [comment] 2018-03-04 03:50
SABS crash https://imgur.com/gallery/ddwZP

I'm still seeing it on 0.0.8.

**Comment by Mike-BITW** [comment] 2018-03-04 04:01
I'll let LayoutXML deal with your crash issue, but for the eBay matter, it's likely that you are using the default package that blacklists both "*.yimg.com" and "*yimg.com".  That second wildcard can't be overridden by whitelisting "i.ebayimg.com".  Until there's a corrected standard package, simply switch to @mmotti's version if you'd rather not whitelist eBay completely.

**Comment by CitizenXVIL** [comment] 2018-03-04 04:12
I just whitelisted *yimg.com and ebay images are fine.

**Comment by LayoutXML** [comment] 2018-03-04 10:29
@kennethpangky What method did you use to change package id? After googling the issue it seems like it is caused by refactoring app in Android Studio. I recommend not touching anything but packagename in gradle file. You don't need to refactor anything.

@CitizenXVIL I have just removed this domain from standard package. Images on ebay should no longer get blocked.

@MGFlaccid & @kennethpangky, please use Android Studio logcat to determine the cause of crash. I can't fix it if I don't know why it crashes for you.

**Comment by kennethpangky** [comment] 2018-03-04 10:54
@LayoutXML I'm just using the APK Editor Pro as recommended in the XDA thread. Have no desire to install Android Studio on my PC. Any other way to track down the issue?

It used to work before 0.0.7, so I don't think it's a "refactor" issue.

**Comment by LayoutXML** [comment] 2018-03-04 11:01
@kennethpangky I didn't change anything with the Welcom Activity on the last few updates. You can attach your modified apk here and I will take a look.

**Comment by kennethpangky** [comment] 2018-03-04 11:05
[com.kennethpk.pang_0.0.8.zip](https://github.com/LayoutXML/SABS/files/1778409/com.kennethpk.pang_0.0.8.zip)

Hi, as requested. Extension changed to zip as Github doesn't allow me to upload an apk.

**Comment by LayoutXML** [comment] 2018-03-04 11:30
@kennethpangky I have reviewed the apk file. Some users experience crashing after updating the app. Can you try uninstalling and installing apk file again? You don't have to recompile with a different package name, and your license key should stay in the app.

**Comment by kennethpangky** [comment] 2018-03-04 11:57
@LayoutXML Same issue. It installs fine, I can enable and disable the standard package. But trying to enter the app selection results in the same crash.

Or is it a theme or font issue? I do have Substratum in use.

**Comment by LayoutXML** [comment] 2018-03-04 12:01
@kennethpangky Try out this apk:
[app-release.zip](https://github.com/LayoutXML/SABS/files/1778455/app-release.zip)

Rename zip to apk first.

**Comment by kennethpangky** [comment] 2018-03-04 14:16
@LayoutXML Thanks for the quick reply. 

I changed the package name, installed over existing, same issue. Uninstalled, reinstalled, same issue. I uninstalled all Substratum related overlays, but issue still exists.

**Comment by LayoutXML** [comment] 2018-03-04 14:48
This is really weird. There are like 10 people with the same issue and over 7000 without. I'm not sure what's different and how to fix it.

**Comment by Mike-BITW** [comment] 2018-03-04 14:53
Since getting proper logs seems unlikely, it might be useful to track which  specific device, SDK level, Knox version, and even CSC those users have in common.  It could still be simple user errors, though.

**Comment by kennethpangky** [comment] 2018-03-04 14:55
If I went back to 0.0.6 and that menu still works would it at least help narrow down something?

**Comment by kennethpangky** [comment] 2018-03-04 15:02
Yup, 0.0.6 still works, at least for that singular bug.

**Comment by LayoutXML** [comment] 2018-03-04 16:01
I'll take a look

**Comment by kennethpangky** [comment] 2018-03-09 16:51
Hi, any idea what caused the issue?

**Comment by Mike-BITW** [comment] 2018-03-09 16:57
Any chance you could try again with the latest build (#518), or at least take another shot at patching the 0.0.8 released apk (#497) with APK Editor Pro (and ZipSigner, maybe)?

**Comment by mmotti** [comment] 2018-03-09 16:59
I don't think we are seeing the correct section of the logs.

I can see debug / info but no fatal errors.

**Comment by Mike-BITW** [comment] 2018-03-09 17:18
OK, I took the plunge, uninstalled all previous SABS from my N8, then started from scratch with the com.kennethpk.pang_0.0.8.apk provided by @kennethpangky.  Guess what: **IT WORKED FLAWLESSLY**, including enabling/disabling blocking in any app. 

This is on my SM-N950U (not SM-N950F/DS)
Using default TMO's CSC, latest official Samsung 7.1.1,  no theming apps, no system apps disabled during testing, as plain as I could reasonably make it.

**Comment by kennethpangky** [comment] 2018-03-09 18:24
Unless there has been a new 0.0.8, it's still not working on my N950F/DS sadly. Looks like I have to stick to 0.0.6 for some unknown reason.

**Comment by Mike-BITW** [comment] 2018-03-09 18:32
No new premasticated apk, if that's what you mean, but many changes in the current sources since build 497. The fact that the apk you uploaded works on my N8 suggests that SOMETHING in your configuration is awry, but we can't guess what it might be from here.  Please investigate any change you might have made to your system (disabled apps, anything that tampers with the UI, etc.).  If you could find a log that documents what happens, it would be extremely useful.

**Comment by LayoutXML** [comment] 2018-03-09 18:56
Please provide logs from Android Studio. I can't fix the issue if there is no issue to be fixed. I'll close this if I nobody who encounters crashes shares the log because it seems like this is not a big issue if no one cares

**Closed** 2018-03-13 03:14 UTC
Labels: bug
