### ISSUE TITLE
2-line URL overwrites number of entries

### ISSUE THREAD

**Issue by Mike-BITW** [LayoutXML/SABS#20] opened 2018-03-03 13:45 UTC
Not really new and not much of an issue, but a reminder that it's still there as of build 494. See the last provider in the screenshot.

![screenshot_20180228-145142](https://user-images.githubusercontent.com/15041712/36934935-7e29e5d6-1eb6-11e8-9322-1741b90e5c24.jpg)

**Comment by LayoutXML** [comment] 2018-03-03 14:37
![screenshot_20180303-163457 1](https://user-images.githubusercontent.com/34867100/36935488-090e7ff0-1f01-11e8-868f-8e27e4589908.jpg)
![screenshot_20180303-163512 1](https://user-images.githubusercontent.com/34867100/36935492-0fd050e8-1f01-11e8-8283-0a92403287d0.jpg)
I can't reproduce the issue. It's really weird that you can't see it. I've got to do more tests with this but it also doesn't happen with files I've tried with.

**Comment by LayoutXML** [comment] 2018-03-03 14:52
I suspect that this got somehow squashed. Try it our with the latest commit - I think I've found a workaround. Let me know if it is fixed now

**Comment by Mike-BITW** [comment] 2018-03-03 14:52
Don't spend too much time on this. I see it even when I use a fresh copy from your current source, without doing anything to it at all. If I enter your standard package's full URL as in your screenshot, it then shows simply as "Standard package" (and apparently overwrites the default "Standard package" entry since it now appears at the bottom).  Have you tried with a local file name? ("/storage/...")?

I'm wondering if it wouldn't be better to only display the tail of those long URLs (showing the actual file name) with the ability to display/edit the full URL from a long press.

**Closed** 2018-03-03 15:00 UTC
